backend:
  name: github
  repo: ghimireaacs/ghimireaacs.github.io
  branch: main
  auth_type: implicit
  app_id: "Ov23lifdvRXO8FdBuH37"

# 1. Global media folder (required). This will be the default for thumbnails.
media_folder: "assets/img/headers"
public_folder: "/assets/img/headers"

# 2. Global media library configuration (required).
media_library:
  name: image
  config:
    multiple: false

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - label: "Body"
        name: "body"
        widget: "markdown"
        # 3. Specific override for images uploaded in the post body.
        media_folder: "assets/img/posts"
        public_folder: "/assets/img/posts"