name: 'Pull Request'
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  pull-request:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 3.0.2

        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # v1.152.0
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Test Site
        run: bash tools/test.sh
        env:
          JEKYLL_ENV: production

